import { PageLoader } from "@/components";
import "@/styles/globals.css";
import StyledComponentsRegistry from "@/components/StyledComponentsRegistry";
import Theme from "@/context/FontContext";
import { UserContextProvider } from "@/context";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <PageLoader /> */}
        <StyledComponentsRegistry>
          <Theme>
            <UserContextProvider>{children}</UserContextProvider>
          </Theme>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
