import { PageLoader } from "@/components";
import "../../styles/globals.css"
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <PageLoader />
        {children}
      </body>
    </html>
  );
}
