import { Leftbar, Topbar } from "@/components";
import "../../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row gap-5 bg-gray-200">
          <Leftbar />
          <div className="flex flex-col w-full h-full">
            <Topbar />
            {children}
          </div>
          l
        </div>
      </body>
    </html>
  );
}
