import { SignUpSection } from "@/components/signUp.page";
import React from "react";

export const metadata = {
  title: "Sign Up | Campus Book Swap",
  description: "Generated by Next.js",
};

const SignUp = () => {
  return <SignUpSection />;
};

export default SignUp;
