import { SignInSection } from "@/components";

export const metadata = {
  title: "Sign In | Campus Book Swap",
  description: "Generated by Next.js",
};


const SignIn = () => {
  return (<SignInSection/>)
};

export default SignIn;
